// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ubrpczopgojsmquufood.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVicnBjem9wZ29qc21xdXVmb29kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxNzQwOTUsImV4cCI6MjA2NTc1MDA5NX0.fB-BK3QtMGG24Shbt5bcuCy61zqEU0Yg8gJgpIaUm5k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);