// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pwbhgthyfofvrjwocztp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB3YmhndGh5Zm9mdnJqd29jenRwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxNjk5OTgsImV4cCI6MjA2NTc0NTk5OH0.XvnBaKY6JOU2B6xSR3fiXEurXjyNi3We8m6goa6ZnKs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);